services:
  mysql_db:
    image: mysql:8.4
    container_name: mysql_84_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma_container
    restart: always
    ports:
      - "13306:80"
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
    depends_on:
      - mysql_db

volumes:
  mysql_data: